version: "3.8"
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kafka
      MYSQL_USER: kafka
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: toor
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
  producer:
    build: producer
    container_name: producer
    ports:
      - "8088:8088"
    expose:
      - "8088"
    depends_on:
      - kafka
  consumer:
    build: consumer
    container_name: consumer
    ports:
      - "8089:8089"
    expose:
      - "8089"
    environment:
      MYSQL_HOST: jdbc:mysql://mysql:3306/kafka
      MYSQL_USER: kafka
      MYSQL_PASSWORD: test
    depends_on:
      - mysql
      - kafka
volumes:
  mysql_data:
  zookeeper_data:
  kafka_data:
